CREATE OR REPLACE VIEW WMS_PKT_8068 AS
SELECT DISTINCT
           fn_cd_master_id_tocode_8068(im.cd_master_id)     AS client_id,
           fn_cd_master_id_toDesc_8068(im.cd_master_id)     AS client_name,
           pi.stat_code,
           ph.pkt_ctrl_nbr                                  AS unique_id,
           NVL (ph.pro_nbr, ph.pkt_ctrl_nbr)                AS pkt_nbr,
           ph.terms_code,
           ph.shipto_addr_3                                 AS TTN,
           ph.shipto,
           ph.shipto_city,
           ph.shipto_zip,
           ph.shipto_name,
           ph.shipto_addr_1,
           ph.shipto_addr_2,
           ph.shipto_contact,
           ph.soldto,
           ph.soldto_name,
           ph.soldto_addr_1,
           pd.pkt_seq_nbr,
           im.size_desc                                     AS sku_wms,
           im.vendor_item_nbr                               AS sku_client,
           pd.orig_pkt_qty,
           (SELECT SUM (ccd.units_pakd)
              FROM carton_dtl ccd
             WHERE ccd.carton_nbr = cd.carton_nbr
                   AND ccd.pkt_seq_nbr = cd.pkt_seq_nbr)    AS units_pakd,
           im.sku_brcd,
           pd.prod_stat,
           pd.batch_nbr,
           im.sku_desc,
           pd.price,
           pd.retail_price,
           pd.unit_monetary_value                           AS unit_price,
           im.unit_ht,
           im.unit_len,
           im.unit_width,
           im.unit_wt,
           ch.carton_nbr,
           pi.mod_date_time,
           ph.plan_load_nbr                                 AS load_nbr -- 11.10.2021
      FROM pkt_hdr  ph
           JOIN pkt_dtl pd ON pd.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
           JOIN pkt_hdr_intrnl pi ON pi.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
           JOIN item_master im ON im.sku_id = pd.sku_id
           JOIN carton_hdr ch ON ch.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
           JOIN carton_dtl cd ON cd.carton_nbr = ch.carton_nbr
                  AND cd.pkt_seq_nbr = pd.pkt_seq_nbr
                  AND cd.sku_id = im.sku_id
     WHERE im.cd_master_id IN ('18005',
                               '10004',
                               '18004',
                               '11004',
                               '6003',
                               '4003',
                               '5004',
                               '9004',
                               '9005',
                               '9006',
                               '5003',
                               '12004',
                               '17004',
                               '13004',
                               '15004',
                               '3001',
                               '3003',
                               '10003')
           AND pi.stat_code > '39' AND pi.stat_code < '91'
    UNION

    SELECT DISTINCT
           fn_cd_master_id_tocode_8068(im.cd_master_id)  AS client_id,
           fn_cd_master_id_toDesc_8068(im.cd_master_id)  AS client_name,
           pi.stat_code,
           ph.pkt_ctrl_nbr                               AS unique_id,
           NVL (ph.pro_nbr, ph.pkt_ctrl_nbr)             AS pkt_nbr,
           ph.terms_code,
           ph.shipto_addr_3                              AS TTN,
           ph.shipto,
           ph.shipto_city,
           ph.shipto_zip,
           ph.shipto_name,
           ph.shipto_addr_1,
           ph.shipto_addr_2,
           ph.shipto_contact,
           ph.soldto,
           ph.soldto_name,
           ph.soldto_addr_1,
           pd.pkt_seq_nbr,
           im.size_desc,
           im.vendor_item_nbr,
           pd.orig_pkt_qty,
           pd.orig_pkt_qty,
           im.sku_brcd,
           pd.prod_stat,
           pd.batch_nbr,
           im.sku_desc,
           pd.price,
           pd.retail_price,
           pd.unit_monetary_value                        AS unit_price,
           im.unit_ht,
           im.unit_len,
           im.unit_width,
           im.unit_wt,
           NULL,
           pi.mod_date_time,
           ph.plan_load_nbr                              AS load_nbr      -- 11.10.2021
      FROM pkt_hdr  ph
           JOIN pkt_dtl pd ON pd.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
           JOIN pkt_hdr_intrnl pi ON pi.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
           JOIN item_master im ON im.sku_id = pd.sku_id
     WHERE im.cd_master_id IN ('18005',
                               '10004',
                               '18004',
                               '11004',
                               '6003',
                               '4003',
                               '5004',
                               '9004',
                               '9005',
                               '9006',
                               '5003',
                               '12004',
                               '17004',
                               '13004',
                               '15004',
                               '3001',
                               '3003',
                               '10003')
           AND (pi.stat_code < '40' OR pi.stat_code > '90')
    UNION ALL
      SELECT client_id,
             client_name,
             stat_code,
             unique_id,
             pkt_nbr,
             terms_code,
             TTN,
             shipto,
             shipto_city,
             shipto_zip,
             shipto_name,
             shipto_addr_1,
             shipto_addr_2,
             shipto_contact,
             soldto,
             soldto_name,
             soldto_addr_1,
             ROW_NUMBER () OVER (PARTITION BY unique_id ORDER BY unique_id, sku_client) num
             pkt_seq_nbr,
             sku_wms,
             sku_client,
             orig_pkt_qty,
             SUM (units_pakd),
             sku_brcd,
             prod_stat,
             batch_nbr,                                          -- 16.02.2022
             sku_desc,
             price,
             retail_price,
             unit_price,
             unit_ht,
             unit_len,
             unit_width,
             unit_wt,
             ' ',
             mod_date_time,
             load_nbr                                            -- 11.10.2021
        FROM (SELECT '00029'                           AS client_id,
                     'Вайн Хантер'                     AS client_name,
                     pi.stat_code,
                     ph.pkt_ctrl_nbr                   AS unique_id,
                     NVL (ph.pro_nbr, ph.pkt_ctrl_nbr) AS pkt_nbr,
                     ph.terms_code,
                     ph.shipto_addr_3                  AS TTN,
                     ph.shipto,
                     ph.shipto_city,
                     ph.shipto_zip,
                     ph.shipto_name,
                     ph.shipto_addr_1,
                     ph.shipto_addr_2,
                     ph.shipto_contact,
                     ph.soldto,
                     ph.soldto_name,
                     ph.soldto_addr_1,
                     pd.pkt_seq_nbr,
                     im.size_desc                      AS sku_wms,
                     im.vendor_item_nbr                AS sku_client,
                     pd.orig_pkt_qty                   AS orig_pkt_qty,-- 2022.07.18
                     --(SELECT SUM (ccd.units_pakd)
                        --FROM carton_dtl ccd
                       --WHERE ccd.carton_nbr = cd.carton_nbr
                             --AND ccd.pkt_seq_nbr = cd.pkt_seq_nbr)
                     cd.units_pakd                     AS units_pakd,-- 2022.07.18
                     im.sku_brcd,
                     pd.prod_stat,
                     NVL (pd.batch_nbr, '*')           AS batch_nbr, -- 16.02.2022
                     im.sku_desc,
                     pd.price,
                     pd.retail_price,
                     pd.unit_monetary_value            AS unit_price,
                     im.unit_ht,
                     im.unit_len,
                     im.unit_width,
                     im.unit_wt,
                     ch.carton_nbr,
                     pi.mod_date_time,
                     ph.plan_load_nbr                  AS load_nbr -- 11.10.2021
                FROM pkt_hdr ph
                     JOIN pkt_dtl pd ON pd.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
                     JOIN pkt_hdr_intrnl pi ON pi.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
                     JOIN item_master im ON im.sku_id = pd.sku_id
                     JOIN carton_hdr ch ON ch.pkt_ctrl_nbr = ph.pkt_ctrl_nbr
                     JOIN carton_dtl cd ON cd.carton_nbr = ch.carton_nbr
                          AND cd.pkt_seq_nbr = pd.pkt_seq_nbr
               WHERE im.cd_master_id = '20004' AND pi.stat_code > '39' AND pd.pkt_ctrl_nbr = 'VH6434' AND im.size_desc = '000292274')
    GROUP BY client_id,
             client_name,
             stat_code,
             unique_id,
             pkt_nbr,
             terms_code,
             TTN,
             shipto,
             shipto_city,
             shipto_zip,
             shipto_name,
             shipto_addr_1,
             shipto_addr_2,
             shipto_contact,
             soldto,
             soldto_name,
             soldto_addr_1,
             sku_wms,
             sku_client,
             sku_brcd,
             sku_desc,
             price,
             retail_price,
             unit_price,
             unit_ht,
             unit_len,
             unit_width,
             unit_wt,
             mod_date_time,
             prod_stat,
             load_nbr,
             batch_nbr,
             pkt_seq_nbr,
             orig_pkt_qty;